package com.project.entity;

import java.util.Date;

/**
 * 角色表
 * @author huangh
 */
public class Role {

    /** ID */
    private Integer id;

    /** 角色名称 */
    private String name;

    /** 0有效 -1无效 */
    private Integer status;

    /** 创建时间 */
    private Date createtime;

    /** 角色菜单权限组，逗号分隔 */
    private String menuids;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.status
     *
     * @return the value of role.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.status
     *
     * @param status the value for role.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.createtime
     *
     * @return the value of role.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.createtime
     *
     * @param createtime the value for role.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.menuids
     *
     * @return the value of role.menuids
     *
     * @mbggenerated
     */
    public String getMenuids() {
        return menuids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.menuids
     *
     * @param menuids the value for role.menuids
     *
     * @mbggenerated
     */
    public void setMenuids(String menuids) {
        this.menuids = menuids;
    }
}